//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.endereco = new HashSet<endereco>();
            this.promocao = new HashSet<promocao>();
            this.telefone = new HashSet<telefone>();
        }
    
        public long codigo_cli { get; set; }
        public string nome_cli { get; set; }
        public string documento_cli { get; set; }
        public sbyte tipoDocumento_cli { get; set; }
        public string nomeFantasia_cli { get; set; }
        public string contato_cli { get; set; }
        public Nullable<long> useralt_cli { get; set; }
        public long usercad_cli { get; set; }
        public System.DateTime datacad_cli { get; set; }
        public Nullable<System.DateTime> dataalt_cli { get; set; }
        public string cloudId_cli { get; set; }
        public string imagem_cli { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual ICollection<endereco> endereco { get; set; }
        public virtual ICollection<promocao> promocao { get; set; }
        public virtual ICollection<telefone> telefone { get; set; }
    }
}
