//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public long codigo_end { get; set; }
        public long codigoCli_end { get; set; }
        public bool ativo_end { get; set; }
        public string cep_end { get; set; }
        public string logradouro_end { get; set; }
        public string numero_end { get; set; }
        public string referencia_end { get; set; }
        public Nullable<System.DateTime> datacad_end { get; set; }
        public long usercad_end { get; set; }
        public Nullable<long> useralt_end { get; set; }
        public Nullable<System.DateTime> dataalt_end { get; set; }
        public string latitude_end { get; set; }
        public string longitude_end { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
