//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagem
    {
        public imagem()
        {
            this.promocao = new HashSet<promocao>();
        }
    
        public long codigo_img { get; set; }
        public string urlRelativa_img { get; set; }
    
        public virtual ICollection<promocao> promocao { get; set; }
    }
}
