//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocaorequerida
    {
        public long codigo_proreq { get; set; }
        public long Promocao_codigo_proreq { get; set; }
        public string codVoucher_proreq { get; set; }
        public System.DateTime validade_proreq { get; set; }
        public System.DateTime datacad_proreq { get; set; }
        public string userCloudId_proreq { get; set; }
        public sbyte status_proreq { get; set; }
        public Nullable<System.DateTime> datastatus_proreq { get; set; }
        public bool foraregra_proreq { get; set; }
    
        public virtual promocao promocao { get; set; }
    }
}
