//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocaorequerida
    {
        public promocaorequerida()
        {
            this.ativa_proreq = true;
        }
    
        public long codigo_proreq { get; set; }
        public long promocao_proreq { get; set; }
        public System.DateTime validade_proreq { get; set; }
        public System.DateTime datacad_proreq { get; set; }
        public string userCloudId_proreq { get; set; }
        public string codVoucher_proreq { get; set; }
        public bool ativa_proreq { get; set; }
    
        public virtual promocao promocao { get; set; }
    }
}
