//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocao
    {
        public promocao()
        {
            this.promocaorequerida = new HashSet<promocaorequerida>();
            this.categoria = new HashSet<categoria>();
        }
    
        public long codigo_pro { get; set; }
        public string titulo_pro { get; set; }
        public string descricao_pro { get; set; }
        public Nullable<long> imagem_pro { get; set; }
        public System.DateTime inicio_pro { get; set; }
        public System.DateTime fim_pro { get; set; }
        public int totalTickets_pro { get; set; }
        public bool limitada_pro { get; set; }
        public long cliente_pro { get; set; }
        public string latitude_pro { get; set; }
        public string longitude_pro { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual imagem imagem { get; set; }
        public virtual ICollection<promocaorequerida> promocaorequerida { get; set; }
        public virtual ICollection<categoria> categoria { get; set; }
    }
}
