//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefone
    {
        public long codigo_tel { get; set; }
        public long codigoCli_tel { get; set; }
        public string ddd_tel { get; set; }
        public string fone_tel { get; set; }
        public sbyte tipofone_tel { get; set; }
        public string contato_tel { get; set; }
        public System.DateTime datacad_tel { get; set; }
        public Nullable<System.DateTime> dataalt_tel { get; set; }
        public long usercad_tel { get; set; }
        public Nullable<long> useralt_tel { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
