//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariocategoria
    {
        public string userCloudId_usucat { get; set; }
        public long Categoria_codigo_cat { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
