//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vale24hWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vale24hEntities : DbContext
    {
        public vale24hEntities()
            : base("name=vale24hEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<imagem> imagem { get; set; }
        public virtual DbSet<promocao> promocao { get; set; }
        public virtual DbSet<promocaorequerida> promocaorequerida { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuariocategoria> usuariocategoria { get; set; }
    }
}
